#!/bin/sh -e

help_error() {
  echo 'Usage: asdf use <plugin> <version>' >&2
  exit 1
}

plugin=$1; shift || help_error
version=$1; shift || help_error

versions=$(asdf list "$plugin" | sort --version-sort --reverse)

for candidate in $versions; do
    if [ "$candidate" = "$version" ]; then
        asdf export-shell-version sh "$plugin" "$version"
        echo "using $plugin version $version" >&2
        exit
    fi
done

escaped_version=$(echo "$version" | sed 's/\./\\./g')

# Use `:` (no-op) if fail to prevent crash
match=$(echo "$versions" | grep -E "^\s*$escaped_version\." | sed 's/ //g' || :)

if [ -z "$match" ]; then
    echo "no version match $version for $plugin" >&2
    echo >&2
    echo "available versions:" >&2
    echo "$versions" >&2
    exit 1
fi

asdf export-shell-version sh "$plugin" "$match"
echo "using $plugin version $match" >&2
